[package]
name = "quickapi"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4" }
sea-orm = { version = "1.2.0-rc.1", features = ["sqlx-postgres", "runtime-tokio"] }
serde = { version = "1.0", features = ["derive"] }